# Goreleaser-compatible SUSE-based image
# Binary is built externally and copied in
FROM registry.suse.com/bci/bci-micro@sha256:44f5c047210188eb290414c52f883b763efa1e234c2a15c325f03e83f0984fa6

LABEL org.opencontainers.image.source="https://github.com/manno/logging-operator"
LABEL org.opencontainers.image.vendor="SUSE Rancher"

# Copy pre-built binary (from goreleaser build or local build)
COPY logging-operator /usr/local/bin/logging-operator

USER 65532:65532

ENTRYPOINT ["/usr/local/bin/logging-operator"]
