# Goreleaser-compatible SUSE-based image
# Binary is built externally and copied in
FROM registry.suse.com/bci/bci-micro@sha256:3e35921219f3156fe67d59c17db0d85b2afa22e706585f214d80dc773b83cba3

LABEL org.opencontainers.image.source="https://github.com/manno/logging-operator"
LABEL org.opencontainers.image.vendor="SUSE Rancher"

# Copy pre-built binary (from goreleaser build or local build)
COPY logging-operator /usr/local/bin/logging-operator

USER 65532:65532

ENTRYPOINT ["/usr/local/bin/logging-operator"]
